# Server Configuration
server.port=3000

# SQLite Datasource Configuration
spring.datasource.url=jdbc:sqlite:database/attendance.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Keep Connection Open for WAL mode performance
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.idle-timeout=10000

# Allow JSON binding to parse request bodies smoothly
spring.mvc.converters.preferred-json-mapper=jackson
